name: flutter_bs_ad_calendar
description: Flutter package to switch between nepali and english calendar easily and efficently.
version: 1.1.0
# homepage: https://github.com/BwesShr/flutter_bs_ad_calendar
homepage: https://github.com/maheshshrestha558/nepali-calender



environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  nepali_utils: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
